package com.payment.exception;

public enum ErrorCode {
    ACCOUNT_NOT_FOUND,
    INSUFFICIENT_BALANCE,
    DUPLICATE_TRANSACTION,
    INVALID_AMOUNT,
    ACCOUNT_ALREADY_EXISTS,
    TRANSACTION_NOT_FOUND,
    INVALID_REQUEST,
    UNAUTHORIZED
}
